name: Update README.md

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md file
        uses: ./ # Uses an action in the root directory
        with:
          src-file-path: test_results.log
          dst-file-path: README.test.md
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-user-name: "GitHubActions"
          git-user-email: "GitHubActions@GitHub.Actions"
          git-commit-msg: "Updated by GitHubActions"
          create-backup: true
          backup-file-path: "./"
