name: testing

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".drone.yml"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare source file
        run: |
          echo "<div>$(whoami)</div>" > test_results.log
      - name: Update README.md file
        uses: ./ # Uses an action in the root directory
        with:
          src-file-path: "test_results.log"
          dst-file-path: "README.test.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
      - name: Prepare original source file
        run: |
          echo "<div>User name will appear here instead</div>" > "test_results.log"
      - name: Revert README.test.md file
        uses: ./ # Uses an action in the root directory
        with:
          src-file-path: "test_results.log"
          dst-file-path: "README.test.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"

  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare source file
        run: |
          echo "<div>$(whoami)</div>" > test_results.log
      - name: Update README.md file
        uses: ./ # Uses an action in the root directory
        with:
          src-file-path: "test_results.log"
          dst-file-path: "README.test.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-skip-push: true
      - name: Prepare original source file
        run: |
          echo "<div>User name will appear here instead</div>" > "test_results.log"
      - name: Revert README.test.md file
        uses: ./ # Uses an action in the root directory
        with:
          src-file-path: "test_results.log"
          dst-file-path: "README.test.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-skip-push: true
